// <auto-generated />
using System;
using DedsiNative.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Volo.Abp.EntityFrameworkCore;

#nullable disable

namespace DedsiNative.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(DedsiNativeDbContext))]
    [Migration("20260822073312_Add_Fine_Grained_Management_Permissions")]
    partial class Add_Fine_Grained_Management_Permissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.PostgreSql)
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DedsiNative.Dictionaries.Dictionary", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatorName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SystemId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("SystemId", "Name")
                        .IsUnique();

                    b.ToTable("Dictionaries", "DedsiNative");
                });

            modelBuilder.Entity("DedsiNative.Dictionaries.DictionaryItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("DictionaryId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ParentId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<int>("Sort")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("DictionaryId", "Code")
                        .IsUnique();

                    b.HasIndex("DictionaryId", "ParentId");

                    b.ToTable("DictionaryItems", "DedsiNative");
                });

            modelBuilder.Entity("DedsiNative.LoginAudits.LoginAudit", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FailureDescription")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("LoginTimeUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("LoginTimeUtc");

                    b.HasIndex("Account", "LoginTimeUtc");

                    b.HasIndex("UserId", "LoginTimeUtc");

                    b.ToTable("LoginAudits", "DedsiNative");
                });

            modelBuilder.Entity("DedsiNative.Menus.Menu", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Component")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatorName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsAffix")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<bool>("KeepAlive")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ParentId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("PermissionId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("PermissionName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Redirect")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RoutePath")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Sort")
                        .HasColumnType("integer");

                    b.Property<string>("SystemId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("SystemId", "Code")
                        .IsUnique();

                    b.HasIndex("SystemId", "ParentId");

                    b.ToTable("Menus", "DedsiNative");
                });

            modelBuilder.Entity("DedsiNative.Organizations.Organization", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("DeleterId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("DeletionTime");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name1")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name2")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name3")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name4")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ParentId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<int>("Sort")
                        .HasColumnType("integer");

                    b.Property<string>("SystemId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Sort");

                    b.HasIndex("SystemId", "Code")
                        .IsUnique();

                    b.HasIndex("SystemId", "ParentId");

                    b.ToTable("Organizations", "DedsiNative");
                });

            modelBuilder.Entity("DedsiNative.Permissions.Permission", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatorName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SystemId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("SystemId");

                    b.ToTable("Permissions", "DedsiNative");

                    b.HasData(
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FB2",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "查看登录审计列表和详情。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:login-audits:view",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FB3",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "查看 SSO 客户端、作用域、授权与令牌。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:openiddict:view",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FB4",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "管理 SSO 客户端、作用域、授权与令牌。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:openiddict:manage",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FC0",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "查看系统。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:systems:view",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FC1",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "创建系统。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:systems:create",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FC2",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "修改系统。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:systems:update",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FC3",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "删除系统。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:systems:delete",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FC4",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "查看权限定义。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:permissions:view",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FC5",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "创建权限定义。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:permissions:create",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FC6",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "修改权限定义。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:permissions:update",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FC7",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "删除权限定义。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:permissions:delete",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FC8",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "查看菜单。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:menus:view",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FC9",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "创建菜单。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:menus:create",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FCA",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "修改菜单。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:menus:update",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FCB",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "删除菜单。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:menus:delete",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FCC",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "查看岗位。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:positions:view",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FCD",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "创建岗位。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:positions:create",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FCE",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "修改岗位。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:positions:update",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FCF",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "删除岗位。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:positions:delete",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FCG",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "配置岗位权限与组织范围。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:positions:assign",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FCH",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "查看组织机构。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:organizations:view",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FCJ",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "创建组织机构。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:organizations:create",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FCK",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "修改组织机构。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:organizations:update",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FCM",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "删除组织机构。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:organizations:delete",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FCN",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "查看用户。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:users:view",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FCP",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "创建用户。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:users:create",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FCQ",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "修改用户。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:users:update",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FCR",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "删除用户。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:users:delete",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FCS",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "重置用户密码。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:users:reset-password",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FCT",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "分配用户岗位。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:users:assign-position",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FCV",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "查看、预览和下载文件。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:storage:view",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FCW",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "上传文件。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:storage:upload",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FCX",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "删除文件。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:storage:delete",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FCY",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "查看字典及字典项。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:dictionaries:view",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FCZ",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "创建字典及字典项。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:dictionaries:create",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FD0",
                            CreationTime = new DateTime(2026, 8, 4, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "修改字典及字典项。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "system:dictionaries:update",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        });
                });

            modelBuilder.Entity("DedsiNative.Positions.Position", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatorName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SystemId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("SystemId");

                    b.ToTable("Positions", "DedsiNative");

                    b.HasData(
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            CreationTime = new DateTime(2026, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "拥有身份管理系统的基础管理权限。",
                            ExtraProperties = "{}",
                            IsEnabled = true,
                            Name = "系统管理员",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        });
                });

            modelBuilder.Entity("DedsiNative.Positions.PositionOrganization", b =>
                {
                    b.Property<string>("PositionId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("OrganizationId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("PositionId", "OrganizationId");

                    b.ToTable("PositionOrganizations", "DedsiNative");
                });

            modelBuilder.Entity("DedsiNative.Positions.PositionPermission", b =>
                {
                    b.Property<string>("PositionId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("PermissionId")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SystemId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("PositionId", "PermissionId");

                    b.ToTable("PositionPermissions", "DedsiNative");

                    b.HasData(
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FB2",
                            PermissionName = "system:login-audits:view",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FB3",
                            PermissionName = "system:openiddict:view",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FB4",
                            PermissionName = "system:openiddict:manage",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FC0",
                            PermissionName = "system:systems:view",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FC1",
                            PermissionName = "system:systems:create",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FC2",
                            PermissionName = "system:systems:update",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FC3",
                            PermissionName = "system:systems:delete",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FC4",
                            PermissionName = "system:permissions:view",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FC5",
                            PermissionName = "system:permissions:create",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FC6",
                            PermissionName = "system:permissions:update",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FC7",
                            PermissionName = "system:permissions:delete",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FC8",
                            PermissionName = "system:menus:view",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FC9",
                            PermissionName = "system:menus:create",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FCA",
                            PermissionName = "system:menus:update",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FCB",
                            PermissionName = "system:menus:delete",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FCC",
                            PermissionName = "system:positions:view",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FCD",
                            PermissionName = "system:positions:create",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FCE",
                            PermissionName = "system:positions:update",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FCF",
                            PermissionName = "system:positions:delete",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FCG",
                            PermissionName = "system:positions:assign",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FCH",
                            PermissionName = "system:organizations:view",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FCJ",
                            PermissionName = "system:organizations:create",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FCK",
                            PermissionName = "system:organizations:update",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FCM",
                            PermissionName = "system:organizations:delete",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FCN",
                            PermissionName = "system:users:view",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FCP",
                            PermissionName = "system:users:create",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FCQ",
                            PermissionName = "system:users:update",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FCR",
                            PermissionName = "system:users:delete",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FCS",
                            PermissionName = "system:users:reset-password",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FCT",
                            PermissionName = "system:users:assign-position",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FCV",
                            PermissionName = "system:storage:view",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FCW",
                            PermissionName = "system:storage:upload",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FCX",
                            PermissionName = "system:storage:delete",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FCY",
                            PermissionName = "system:dictionaries:view",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FCZ",
                            PermissionName = "system:dictionaries:create",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        },
                        new
                        {
                            PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                            PermissionId = "01ARZ3NDEKTSV4RRFFQ69G5FD0",
                            PermissionName = "system:dictionaries:update",
                            SystemId = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            SystemName = "身份管理系统"
                        });
                });

            modelBuilder.Entity("DedsiNative.StorageFiles.StorageFile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("CreatorId");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid")
                        .HasColumnName("DeleterId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("DeletionTime");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("LastModifierId");

                    b.Property<string>("Md5Hash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("StorageType")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("CreationTime");

                    b.HasIndex("Md5Hash");

                    b.ToTable("StorageFiles", "DedsiNative");
                });

            modelBuilder.Entity("DedsiNative.Systems.System", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatorName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("Systems", "DedsiNative");

                    b.HasData(
                        new
                        {
                            Id = "01ARZ3NDEKTSV4RRFFQ69G5FAV",
                            CreationTime = new DateTime(2026, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Description = "DedsiNative 基础身份与授权管理。",
                            ExtraProperties = "{}",
                            Name = "身份管理系统",
                            Sort = 0
                        });
                });

            modelBuilder.Entity("DedsiNative.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatorName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ExtraProperties");

                    b.Property<string>("IdCardNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("LastLoginIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("LastLoginTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("SoftDeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Users", "DedsiNative");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01951500-0000-7000-8000-000000000001"),
                            CreationTime = new DateTime(2026, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatorId = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatorName = "system",
                            Email = "cohenwang@example.com",
                            ExtraProperties = "{}",
                            LastUpdatedAt = new DateTime(2026, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "CohenWang"
                        });
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("text");

                    b.Property<string>("ClientType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ConsentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text");

                    b.Property<string>("JsonWebKeySet")
                        .HasColumnType("text");

                    b.Property<string>("Permissions")
                        .HasColumnType("text");

                    b.Property<string>("PostLogoutRedirectUris")
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("RedirectUris")
                        .HasColumnType("text");

                    b.Property<string>("Requirements")
                        .HasColumnType("text");

                    b.Property<string>("Settings")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("OpenIddictApplications", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("Scopes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictAuthorizations", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreScope", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Descriptions")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<string>("Resources")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("OpenIddictScopes", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text");

                    b.Property<string>("AuthorizationId")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RedemptionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Type")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId");

                    b.HasIndex("ReferenceId")
                        .IsUnique();

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("OpenIddictTokens", (string)null);
                });

            modelBuilder.Entity("DedsiNative.Dictionaries.Dictionary", b =>
                {
                    b.HasOne("DedsiNative.Systems.System", null)
                        .WithMany()
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DedsiNative.Dictionaries.DictionaryItem", b =>
                {
                    b.HasOne("DedsiNative.Dictionaries.Dictionary", null)
                        .WithMany("Items")
                        .HasForeignKey("DictionaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DedsiNative.Dictionaries.DictionaryItem", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DedsiNative.Menus.Menu", b =>
                {
                    b.HasOne("DedsiNative.Menus.Menu", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DedsiNative.Permissions.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DedsiNative.Systems.System", null)
                        .WithMany()
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DedsiNative.Organizations.Organization", b =>
                {
                    b.HasOne("DedsiNative.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DedsiNative.Systems.System", null)
                        .WithMany()
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DedsiNative.Permissions.Permission", b =>
                {
                    b.HasOne("DedsiNative.Systems.System", null)
                        .WithMany()
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DedsiNative.Positions.Position", b =>
                {
                    b.HasOne("DedsiNative.Systems.System", null)
                        .WithMany()
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DedsiNative.Positions.PositionOrganization", b =>
                {
                    b.HasOne("DedsiNative.Positions.Position", null)
                        .WithMany("Organizations")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DedsiNative.Positions.PositionPermission", b =>
                {
                    b.HasOne("DedsiNative.Positions.Position", null)
                        .WithMany("Permissions")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DedsiNative.Users.User", b =>
                {
                    b.OwnsOne("DedsiNative.Users.UserLoginInfo", "LoginInfo", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Account")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.Property<string>("PasswordHash")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)");

                            b1.Property<string>("PasswordSalt")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)");

                            b1.HasKey("UserId");

                            b1.HasIndex("Account")
                                .IsUnique();

                            b1.ToTable("UserLoginInfos", "DedsiNative");

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.HasData(
                                new
                                {
                                    UserId = new Guid("01951500-0000-7000-8000-000000000001"),
                                    Account = "CohenWang",
                                    PasswordHash = "W/2szOheNj12boeq2Lb+T8mtJsWknqskgTxfEcbPV68=",
                                    PasswordSalt = "AQIDBAUGBwgJCgsMDQ4PEA==",
                                    Status = "Normal"
                                });
                        });

                    b.OwnsMany("DedsiNative.Users.UserOrganization", "Organizations", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("OrganizationId")
                                .HasMaxLength(26)
                                .HasColumnType("character varying(26)");

                            b1.Property<string>("OrganizationName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.HasKey("UserId", "OrganizationId");

                            b1.ToTable("UserOrganizations", "DedsiNative");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsMany("DedsiNative.Users.UserPosition", "Positions", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("PositionId")
                                .HasMaxLength(26)
                                .HasColumnType("character varying(26)");

                            b1.Property<string>("PositionName")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)");

                            b1.HasKey("UserId", "PositionId");

                            b1.ToTable("UserPositions", "DedsiNative");

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.HasData(
                                new
                                {
                                    UserId = new Guid("01951500-0000-7000-8000-000000000001"),
                                    PositionId = "01ARZ3NDEKTSV4RRFFQ69G5FB0",
                                    PositionName = "系统管理员"
                                });
                        });

                    b.Navigation("LoginInfo");

                    b.Navigation("Organizations");

                    b.Navigation("Positions");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Authorizations")
                        .HasForeignKey("ApplicationId");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Tokens")
                        .HasForeignKey("ApplicationId");

                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", "Authorization")
                        .WithMany("Tokens")
                        .HasForeignKey("AuthorizationId");

                    b.Navigation("Application");

                    b.Navigation("Authorization");
                });

            modelBuilder.Entity("DedsiNative.Dictionaries.Dictionary", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DedsiNative.Positions.Position", b =>
                {
                    b.Navigation("Organizations");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Navigation("Authorizations");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
