<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>DedsiNative</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Dedsi.CleanArchitecture.Infrastructure" Version="$(DedsiFrameworkVersion)" />
        <PackageReference Include="Volo.Abp.EntityFrameworkCore.PostgreSql" Version="$(AbpFrameworkVersion)" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DedsiNative.Core\DedsiNative.Core.csproj" />
    </ItemGroup>

</Project>
