<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>DedsiNative</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Dedsi.CleanArchitecture.Infrastructure" Version="$(DedsiFrameworkVersion)" />
        <PackageReference Include="Volo.Abp.BlobStoring.Minio" Version="$(AbpFrameworkVersion)" />
        <PackageReference Include="Volo.Abp.EntityFrameworkCore.PostgreSql" Version="$(AbpFrameworkVersion)" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DedsiNative.Core\DedsiNative.Core.csproj" />
    </ItemGroup>

</Project>
