<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>DedsiNative</RootNamespace>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <Using Include="Microsoft.AspNetCore.Http" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FastEndpoints" Version="8.2.0" />
        <PackageReference Include="FastEndpoints.OpenApi" Version="8.2.0" />
        <PackageReference Include="Microsoft.OpenApi" Version="2.11.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.2" />
        <PackageReference Include="Dedsi.CleanArchitecture.HttpApi" Version="$(DedsiFrameworkVersion)" />
        <PackageReference Include="OpenIddict.Abstractions" Version="7.6.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DedsiNative.Infrastructure\DedsiNative.Infrastructure.csproj" />
    </ItemGroup>

</Project>
