using DedsiNative.Menus;
using DedsiNative.Permissions;
using DedsiNative.Systems;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SystemEntity = DedsiNative.Systems.System;
namespace DedsiNative.EntityFrameworkCore.Configurations;
public sealed class MenuConfiguration : IEntityTypeConfiguration<Menu>
{ public void Configure(EntityTypeBuilder<Menu> b) { b.ToTable("Menus", DedsiNativeCoreConsts.DbSchemaName); b.HasKey(x=>x.Id); b.Property(x=>x.Id).HasMaxLength(26).IsRequired(); b.Property(x=>x.SystemId).HasMaxLength(26).IsRequired(); b.Property(x=>x.SystemName).HasMaxLength(SystemConsts.MaxNameLength).IsRequired(); b.Property(x=>x.Code).HasMaxLength(MenuConsts.MaxCodeLength).IsRequired(); b.Property(x=>x.Name).HasMaxLength(MenuConsts.MaxNameLength).IsRequired(); b.Property(x=>x.ParentId).HasMaxLength(26); b.Property(x=>x.Type).HasConversion<int>(); b.Property(x=>x.RoutePath).HasMaxLength(MenuConsts.MaxRouteLength); b.Property(x=>x.Component).HasMaxLength(MenuConsts.MaxRouteLength); b.Property(x=>x.Redirect).HasMaxLength(MenuConsts.MaxRouteLength); b.Property(x=>x.Icon).HasMaxLength(MenuConsts.MaxIconLength); b.Property(x=>x.PermissionId).HasMaxLength(26); b.Property(x=>x.PermissionName).HasMaxLength(PermissionConsts.MaxNameLength); b.Property(x=>x.ExternalUrl).HasMaxLength(MenuConsts.MaxExternalUrlLength); b.Property(x=>x.Description).HasMaxLength(MenuConsts.MaxDescriptionLength); b.Property(x=>x.CreationTime).IsRequired(); b.Property(x=>x.CreatorId).IsRequired(); b.Property(x=>x.CreatorName).HasMaxLength(64); b.Property(x=>x.ConcurrencyStamp).HasMaxLength(40).IsConcurrencyToken(); b.HasIndex(x=>new{x.SystemId,x.Code}).IsUnique(); b.HasIndex(x=>new{x.SystemId,x.ParentId}); b.HasIndex(x=>x.PermissionId); b.HasOne<SystemEntity>().WithMany().HasForeignKey(x=>x.SystemId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Permission>().WithMany().HasForeignKey(x=>x.PermissionId).OnDelete(DeleteBehavior.Restrict); b.HasOne<Menu>().WithMany().HasForeignKey(x=>x.ParentId).OnDelete(DeleteBehavior.Restrict); } }
